name: CI Terraform - Apply

on:
  workflow_dispatch:

jobs:
  applying:
    name: Applying infrastructure update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Executing Applying Changes
        run: |
          set +e
          
          cd ./aws

          aws s3 sync s3://{s3-address} .

          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform

          terraform init
          terraform apply -auto-approve

          aws s3 cp terraform.tfstate s3://{s3-address}/terraform.tfstate
          aws s3 cp terraform.tfstate.backup s3://{s3-address}/terraform.tfstate.backup
          